name: optime
description: "Application for students"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.2
  percent_indicator: ^4.2.4
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^21.2.4
  googleapis_auth: ^1.3.0
  connectivity_plus: ^6.1.0
  flutter_tts: ^4.2.0
  bcrypt: ^1.1.3
  flutter_dotenv: ^5.2.1
  dart_amqp: ^0.3.1
  stomp_dart_client: ^2.1.0
  socket_io_client: ^3.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  permission_handler: ^10.2.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/googleicon.png
    - lib/assets/icon/optime.png
    - lib/assets/.env

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/optime.png"